version: "3"
services:
  web:
    container_name: web
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    tty: true
  smtp:
    container_name: smtp
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
  db:
    container_name: db
    image: postgres:16.1
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authjs
    volumes:
      - ./db/data:/var/lib/postgresql/data