version: "3"
services:
  web:
    container_name: web
    image: node:20-alpine3.18
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
    tty: true
    working_dir: /app
    command:
      - "sh"
      - "-c"
      - |
        npm install;
        npm run dev;
  smtp:
    container_name: smtp
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"